<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\AssetLifecycleLog;
use App\Models\Department;
use App\Models\MaintenanceLog;
use App\Models\User;
use App\Models\Vendor;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vendors = Vendor::all();
        $departments = Department::all();
        $users = User::whereIn('role_id', function($query) {
            $query->select('id')
                ->from('roles')
                ->whereIn('name', ['it_staff', 'it_manager']);
        })->get();

        if ($vendors->isEmpty() || $departments->isEmpty() || $users->isEmpty()) {
            $this->command->error('Please seed vendors, departments, and users first!');
            return;
        }

        $assets = $this->getDummyAssets();

        foreach ($assets as $assetData) {
            $asset = Asset::updateOrCreate(
                ['asset_code' => $assetData['asset']['asset_code']],
                $assetData['asset']
            );
            
            // Log creation
            AssetLifecycleLog::create([
                'asset_id' => $asset->id,
                'from_status' => 'procurement',
                'to_status' => $asset->status,
                'reason' => 'Asset created and registered',
                'changed_by' => $users->random()->id,
            ]);

            $this->command->info("Created asset: {$asset->asset_code} - {$asset->name}");
        }

        $this->command->info('Asset seeding completed!');
    }

    /**
     * Get dummy asset data
     */
    protected function getDummyAssets(): array
    {
        $vendors = Vendor::pluck('id')->toArray();
        $departments = Department::pluck('id')->toArray();
        $users = User::pluck('id')->toArray();

        return [
            // HARDWARE ASSETS
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0001',
                    'asset_type' => 'hardware',
                    'name' => 'Dell Latitude 5540 Laptop',
                    'brand' => 'Dell',
                    'model' => 'Latitude 5540',
                    'serial_number' => 'SN-DELL-2024-001',
                    'part_number' => 'PN-LAT5540',
                    'specs' => json_encode([
                        'processor' => 'Intel Core i7-1365U',
                        'ram' => '16GB DDR4',
                        'storage' => '512GB NVMe SSD',
                        'display' => '15.6" FHD',
                        'os' => 'Windows 11 Pro',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => $users[0] ?? null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(3),
                    'assigned_notes' => 'Assigned to IT Support Staff for daily operations',
                    'location' => 'Building A, Floor 2, Room 205',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Dell Indonesia',
                    'purchase_order_number' => 'PO-2024-001',
                    'purchase_date' => now()->subMonths(6),
                    'price' => 18500000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(6),
                    'warranty_end' => now()->addMonths(18),
                    'warranty_provider' => 'Dell Indonesia Warranty Center',
                    'warranty_notes' => '3 years onsite warranty',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 4,
                    'depreciated_value' => 16187500,
                    'depreciation_start_date' => now()->subMonths(6),
                    'notes' => 'Primary laptop for IT support operations',
                ],
                'maintenance_logs' => [
                    [
                        'maintenance_type' => 'preventive',
                        'title' => 'Routine Maintenance',
                        'description' => 'Disk cleanup and antivirus scan',
                        'performed_by' => $users[0] ?? 1,
                        'vendor_name' => null,
                        'cost' => 0,
                        'currency' => 'IDR',
                        'start_date' => now()->subMonths(2),
                        'end_date' => now()->subMonths(2)->addHours(2),
                        'status' => 'completed',
                        'outcome' => 'System running smoothly',
                    ],
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0002',
                    'asset_type' => 'hardware',
                    'name' => 'HP LaserJet Pro M404dn Printer',
                    'brand' => 'HP',
                    'model' => 'LaserJet Pro M404dn',
                    'serial_number' => 'SN-HP-2024-002',
                    'part_number' => 'PN-M404DN',
                    'specs' => json_encode([
                        'print_speed' => '38 ppm',
                        'resolution' => '4800 x 600 dpi',
                        'connectivity' => 'USB, Ethernet',
                        'duplex' => 'Automatic',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(5),
                    'assigned_notes' => 'Shared printer for IT Department',
                    'location' => 'Building A, Floor 2, Room 201',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT HP Indonesia',
                    'purchase_order_number' => 'PO-2024-002',
                    'purchase_date' => now()->subMonths(5),
                    'price' => 4500000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(5),
                    'warranty_end' => now()->addMonths(7),
                    'warranty_provider' => 'HP Service Center',
                    'warranty_notes' => '1 year warranty',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 4125000,
                    'depreciation_start_date' => now()->subMonths(5),
                    'notes' => 'Main printer for IT department',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0003',
                    'asset_type' => 'hardware',
                    'name' => 'Dell PowerEdge R750 Server',
                    'brand' => 'Dell',
                    'model' => 'PowerEdge R750',
                    'serial_number' => 'SN-DELL-SRV-003',
                    'part_number' => 'PN-R750',
                    'specs' => json_encode([
                        'processor' => '2x Intel Xeon Gold 6348',
                        'ram' => '256GB DDR4',
                        'storage' => '8x 1.92TB SSD RAID 10',
                        'raid_controller' => 'PERC H755',
                        'psu' => 'Dual 1100W',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'new',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(2),
                    'assigned_notes' => 'Production server for application hosting',
                    'location' => 'Data Center, Rack 5, U10-U12',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Dell Indonesia',
                    'purchase_order_number' => 'PO-2024-003',
                    'purchase_date' => now()->subMonths(3),
                    'price' => 285000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(3),
                    'warranty_end' => now()->addMonths(45),
                    'warranty_provider' => 'Dell ProSupport',
                    'warranty_notes' => '5 years ProSupport with Next Business Day onsite',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 275625000,
                    'depreciation_start_date' => now()->subMonths(3),
                    'notes' => 'Main production server',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'Firmware update for RAID controller and iDRAC',
                        'cost' => 0,
                        'performed_by' => 'System Administrator',
                        'date' => now()->subMonth(),
                    ],
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0004',
                    'asset_type' => 'hardware',
                    'name' => 'ThinkVision P27h-20 Monitor',
                    'brand' => 'Lenovo',
                    'model' => 'P27h-20',
                    'serial_number' => 'SN-LEN-MON-004',
                    'part_number' => 'PN-P27H-20',
                    'specs' => json_encode([
                        'size' => '27 inch',
                        'resolution' => '2560 x 1440 QHD',
                        'panel' => 'IPS',
                        'ports' => 'HDMI, DP, USB-C',
                    ]),
                    'status' => 'inventory',
                    'condition' => 'new',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => null,
                    'location' => 'Storage Room A2',
                    'vendor_id' => $vendors[0] ?? null,
                    'purchase_order_number' => 'PO-2024-004',
                    'purchase_date' => now()->subMonth(),
                    'price' => 5200000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonth(),
                    'warranty_end' => now()->addYears(3),
                    'warranty_provider' => 'Lenovo Indonesia',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 5113333,
                    'depreciation_start_date' => now()->subMonth(),
                    'notes' => 'Spare monitor, 5 units in stock',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0005',
                    'asset_type' => 'hardware',
                    'name' => 'APC Smart-UPS 3000VA',
                    'brand' => 'APC',
                    'model' => 'SMT3000RMI2U',
                    'serial_number' => 'SN-APC-UPS-005',
                    'part_number' => 'PN-SMT3000',
                    'specs' => json_encode([
                        'capacity' => '3000VA / 2700W',
                        'form_factor' => 'Rack 2U',
                        'battery_type' => 'VRLA',
                        'outlets' => '8x NEMA 5-20R',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(8),
                    'assigned_notes' => 'UPS for server rack',
                    'location' => 'Data Center, Rack 1',
                    'vendor_id' => $vendors[0] ?? null,
                    'purchase_order_number' => 'PO-2023-015',
                    'purchase_date' => now()->subMonths(8),
                    'price' => 32000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(8),
                    'warranty_end' => now()->addMonths(16),
                    'warranty_provider' => 'APC Service Center',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 29866667,
                    'depreciation_start_date' => now()->subMonths(8),
                    'notes' => 'Main UPS for server room',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'Battery health check and firmware update',
                        'cost' => 500000,
                        'performed_by' => 'APC Technician',
                        'date' => now()->subMonths(4),
                    ],
                ],
            ],

            // SOFTWARE ASSETS
            [
                'asset' => [
                    'asset_code' => 'AST-SW-0001',
                    'asset_type' => 'software',
                    'name' => 'Microsoft Windows Server 2022 Datacenter',
                    'brand' => 'Microsoft',
                    'model' => 'Server 2022 Datacenter',
                    'serial_number' => 'LICENSE-MS-WS2022-001',
                    'part_number' => 'P72-08492',
                    'specs' => json_encode([
                        'license_type' => 'Core License (16 cores)',
                        'cal_included' => 'No additional CALs required for Datacenter',
                        'virtualization' => 'Unlimited VMs',
                        'support_ends' => '2031-10-12',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'new',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(6),
                    'assigned_notes' => 'Installed on Dell PowerEdge R750',
                    'location' => 'Data Center',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Microsoft Indonesia',
                    'purchase_order_number' => 'PO-2024-005',
                    'purchase_date' => now()->subMonths(6),
                    'price' => 75000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(6),
                    'warranty_end' => now()->addYears(5),
                    'warranty_provider' => 'Microsoft Support',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 68750000,
                    'depreciation_start_date' => now()->subMonths(6),
                    'notes' => 'Production server OS license',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-SW-0002',
                    'asset_type' => 'software',
                    'name' => 'Microsoft 365 Business Premium Licenses',
                    'brand' => 'Microsoft',
                    'model' => '365 Business Premium',
                    'serial_number' => 'LICENSE-M365-BP-002',
                    'part_number' => null,
                    'specs' => json_encode([
                        'license_type' => 'Subscription (per user/month)',
                        'seats' => '50 users',
                        'includes' => 'Office Apps, Exchange Online, Teams, SharePoint, Intune',
                        'renewal_date' => now()->addMonths(6)->format('Y-m-d'),
                    ]),
                    'status' => 'deployed',
                    'condition' => 'new',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subYear(),
                    'assigned_notes' => 'Company-wide productivity suite',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Microsoft Indonesia',
                    'purchase_order_number' => 'PO-2023-020',
                    'purchase_date' => now()->subYear(),
                    'price' => 150000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subYear(),
                    'warranty_end' => now()->addMonths(6),
                    'warranty_provider' => 'Microsoft 365 Support',
                    'depreciation_method' => 'none',
                    'notes' => 'Annual subscription, renews every January',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-SW-0003',
                    'asset_type' => 'software',
                    'name' => 'Veeam Backup & Replication',
                    'brand' => 'Veeam',
                    'model' => 'Veeam Backup & Replication v12',
                    'serial_number' => 'LICENSE-VEEAM-003',
                    'specs' => json_encode([
                        'license_type' => 'Per Socket (2 sockets)',
                        'instances' => '10 instances',
                        'support_level' => 'Production Support',
                        'maintenance_ends' => now()->addMonths(10)->format('Y-m-d'),
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(14),
                    'assigned_notes' => 'Backup solution for all virtual machines',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'Veeam Partner Indonesia',
                    'purchase_order_number' => 'PO-2023-025',
                    'purchase_date' => now()->subMonths(14),
                    'price' => 45000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(14),
                    'warranty_end' => now()->addMonths(10),
                    'warranty_provider' => 'Veeam Support',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 3,
                    'depreciated_value' => 28750000,
                    'depreciation_start_date' => now()->subMonths(14),
                    'notes' => 'Critical backup infrastructure',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'Upgrade to v12, added new backup repository',
                        'cost' => 0,
                        'performed_by' => 'System Administrator',
                        'date' => now()->subMonths(2),
                    ],
                ],
            ],

            // NETWORK ASSETS
            [
                'asset' => [
                    'asset_code' => 'AST-NW-0001',
                    'asset_type' => 'network',
                    'name' => 'Cisco Catalyst 9200L Switch',
                    'brand' => 'Cisco',
                    'model' => 'C9200L-48P-4X-E',
                    'serial_number' => 'SN-CISCO-SW-001',
                    'part_number' => 'C9200L-48P-4X-E',
                    'specs' => json_encode([
                        'ports' => '48x PoE+ Gigabit + 4x 10G Uplink',
                        'stacking' => 'StackWise-160',
                        'ios_version' => 'IOS XE 17.9.4',
                        'power_budget' => '740W PoE+',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(10),
                    'assigned_notes' => 'Core switch for Building A',
                    'location' => 'Building A, MDF Room, Floor 1',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Cisco Indonesia',
                    'purchase_order_number' => 'PO-2023-030',
                    'purchase_date' => now()->subMonths(10),
                    'price' => 95000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(10),
                    'warranty_end' => now()->addMonths(50),
                    'warranty_provider' => 'Cisco TAC',
                    'warranty_notes' => '5 years DNA Essentials license included',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 7,
                    'depreciated_value' => 83869048,
                    'depreciation_start_date' => now()->subMonths(10),
                    'notes' => 'Core network switch for Building A',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'IOS upgrade to 17.9.4a, security patches applied',
                        'cost' => 0,
                        'performed_by' => 'Network Administrator',
                        'date' => now()->subMonths(3),
                    ],
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-NW-0002',
                    'asset_type' => 'network',
                    'name' => 'FortiGate 200F Firewall',
                    'brand' => 'Fortinet',
                    'model' => 'FortiGate 200F',
                    'serial_number' => 'SN-FORTINET-FG-002',
                    'part_number' => 'FG-200F',
                    'specs' => json_encode([
                        'throughput' => '7.5 Gbps Threat Protection',
                        'interfaces' => '18x GE RJ45, 8x GE SFP, 2x 10GE SFP+',
                        'fortios' => 'FortiOS 7.4.2',
                        'features' => 'IPS, Application Control, Web Filtering, Antivirus',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'new',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(4),
                    'assigned_notes' => 'Main perimeter firewall',
                    'location' => 'Data Center, Rack 1, U5-U6',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Fortinet Indonesia',
                    'purchase_order_number' => 'PO-2024-006',
                    'purchase_date' => now()->subMonths(5),
                    'price' => 125000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(5),
                    'warranty_end' => now()->addMonths(43),
                    'warranty_provider' => 'Fortinet TAC',
                    'warranty_notes' => '5 years FortiGuard UTP bundle',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 7,
                    'depreciated_value' => 117857143,
                    'depreciation_start_date' => now()->subMonths(5),
                    'notes' => 'Primary firewall protecting network perimeter',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'Firmware upgrade to FortiOS 7.4.2, signature database updates',
                        'cost' => 0,
                        'performed_by' => 'Network Administrator',
                        'date' => now()->subMonths(2),
                    ],
                    [
                        'description' => 'Rule optimization and policy cleanup',
                        'cost' => 0,
                        'performed_by' => 'Network Administrator',
                        'date' => now()->subMonth(),
                    ],
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-NW-0003',
                    'asset_type' => 'network',
                    'name' => 'Cisco Catalyst 9120AXI Access Point',
                    'brand' => 'Cisco',
                    'model' => 'C9120AXI-E',
                    'serial_number' => 'SN-CISCO-AP-003',
                    'part_number' => 'C9120AXI-E',
                    'specs' => json_encode([
                        'wifi_standard' => 'Wi-Fi 6 (802.11ax)',
                        'bands' => 'Dual-band (2.4 GHz + 5 GHz)',
                        'max_clients' => '200+ concurrent clients',
                        'throughput' => '4.8 Gbps aggregate',
                        'features' => 'OFDMA, MU-MIMO, BSS Color',
                    ]),
                    'status' => 'deployed',
                    'condition' => 'good',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(7),
                    'assigned_notes' => 'Wireless coverage for Building A Floor 2',
                    'location' => 'Building A, Floor 2, Ceiling',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Cisco Indonesia',
                    'purchase_order_number' => 'PO-2023-035',
                    'purchase_date' => now()->subMonths(8),
                    'price' => 12500000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(8),
                    'warranty_end' => now()->addMonths(40),
                    'warranty_provider' => 'Cisco TAC',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 5,
                    'depreciated_value' => 10833333,
                    'depreciation_start_date' => now()->subMonths(8),
                    'notes' => '1 of 12 APs deployed in Building A',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-NW-0004',
                    'asset_type' => 'network',
                    'name' => 'Cisco Catalyst 9200L Switch (Floor 3)',
                    'brand' => 'Cisco',
                    'model' => 'C9200L-24P-4G-E',
                    'serial_number' => 'SN-CISCO-SW-004',
                    'part_number' => 'C9200L-24P-4G-E',
                    'specs' => json_encode([
                        'ports' => '24x PoE+ Gigabit + 4x 1G Uplink',
                        'ios_version' => 'IOS XE 17.9.4',
                        'power_budget' => '370W PoE+',
                    ]),
                    'status' => 'maintenance',
                    'condition' => 'fair',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => $departments[0] ?? null,
                    'assigned_at' => now()->subMonths(10),
                    'assigned_notes' => 'Distribution switch for Building A Floor 3',
                    'location' => 'Building A, IDF Room, Floor 3',
                    'vendor_id' => $vendors[0] ?? null,
                    'purchase_order_number' => 'PO-2023-030',
                    'purchase_date' => now()->subMonths(10),
                    'price' => 52000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subMonths(10),
                    'warranty_end' => now()->addMonths(50),
                    'warranty_provider' => 'Cisco TAC',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 7,
                    'depreciated_value' => 45777778,
                    'depreciation_start_date' => now()->subMonths(10),
                    'notes' => 'Scheduled for replacement - port capacity reached',
                ],
                'maintenance_logs' => [
                    [
                        'description' => 'Replacing faulty PoE port for AP connection',
                        'cost' => 1500000,
                        'performed_by' => 'Network Administrator',
                        'date' => now()->subDays(3),
                    ],
                ],
            ],

            // Additional assets with various statuses
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0006',
                    'asset_type' => 'hardware',
                    'name' => 'Lenovo ThinkCentre M90q Tiny Desktop',
                    'brand' => 'Lenovo',
                    'model' => 'ThinkCentre M90q',
                    'serial_number' => 'SN-LEN-PC-006',
                    'specs' => json_encode([
                        'processor' => 'Intel Core i5-12500T',
                        'ram' => '16GB DDR4',
                        'storage' => '256GB NVMe SSD',
                        'os' => 'Windows 11 Pro',
                    ]),
                    'status' => 'procurement',
                    'condition' => 'new',
                    'location' => 'Pending delivery',
                    'vendor_id' => $vendors[0] ?? null,
                    'vendor_name' => 'PT Lenovo Indonesia',
                    'purchase_order_number' => 'PO-2026-001',
                    'purchase_date' => now(),
                    'price' => 12500000,
                    'currency' => 'IDR',
                    'warranty_start' => now(),
                    'warranty_end' => now()->addYears(3),
                    'warranty_provider' => 'Lenovo Indonesia',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 4,
                    'depreciated_value' => 12500000,
                    'depreciation_start_date' => now(),
                    'notes' => 'New employee workstation, expected delivery 2 weeks',
                ],
            ],
            [
                'asset' => [
                    'asset_code' => 'AST-HW-0007',
                    'asset_type' => 'hardware',
                    'name' => 'Old Dell OptiPlex 7050 Desktop',
                    'brand' => 'Dell',
                    'model' => 'OptiPlex 7050',
                    'serial_number' => 'SN-DELL-OLD-007',
                    'specs' => json_encode([
                        'processor' => 'Intel Core i5-7500',
                        'ram' => '8GB DDR4',
                        'storage' => '256GB SSD',
                        'os' => 'Windows 10 Pro',
                    ]),
                    'status' => 'retired',
                    'condition' => 'poor',
                    'assigned_to_user_id' => null,
                    'assigned_to_department_id' => null,
                    'location' => 'Storage Room B1 (End of Life)',
                    'vendor_name' => 'Dell Indonesia',
                    'purchase_date' => now()->subYears(5),
                    'price' => 9000000,
                    'currency' => 'IDR',
                    'warranty_start' => now()->subYears(5),
                    'warranty_end' => now()->subYears(2),
                    'warranty_provider' => 'Dell Indonesia',
                    'depreciation_method' => 'straight_line',
                    'useful_life_years' => 4,
                    'depreciated_value' => 0,
                    'depreciation_start_date' => now()->subYears(5),
                    'disposal_date' => null,
                    'disposal_reason' => 'End of life, hardware degradation, no longer supported',
                    'disposal_value' => 500000,
                    'notes' => 'Scheduled for disposal/auction',
                ],
            ],
        ];
    }
}
